language: go
sudo: false

go:
  - 1.9

matrix:
  include:
    - os: linux
      env:
        - RELEASE_DIR=$HOME/release-$TRAVIS_TAG-$TRAVIS_OS_NAME
        - RELEASE_TAR=$RELEASE_DIR.tar.gz
        - BINARY_PATH=$HOME/jira-branch-helper
    - os: osx
      env:
        - RELEASE_DIR=$HOME/release-$TRAVIS_TAG-$TRAVIS_OS_NAME
        - RELEASE_TAR=$RELEASE_DIR.tar.gz
        - BINARY_PATH=$HOME/jira-branch-helper

install:
- go get -u github.com/golang/dep/cmd/dep
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- dep ensure
- go build -o $BINARY_PATH -ldflags "-X main.AppVersion=$TRAVIS_TAG" cmd/jira-branch-helper/jira-branch-helper.go

script:
  - (cd jira/branchhelper && go test)

before_deploy:
  - mkdir $RELEASE_DIR
  - cp $BINARY_PATH $RELEASE_DIR/
  - tar cvzf $RELEASE_TAR $RELEASE_DIR
deploy:
  provider: releases
  api_key:
    secure: Oo3IBQAsWIoVcqfglO0UU0ifDnfLiRkr+a9jEbijLY5nG0/Er0gc7kDqTJ/hN6YhR/Mt704/yRp+Tf0P9F6UCNZTioAN4vLXdnFbh329ljtouDdG7pPc3rlXWmqwn/qr2I8iDIy1ABs1yWQJ7slHEbyDkZ4+6qWaEk3bIt48SCgM7JQaY85k8S+t7oONKgvyKEsFo3qH0f4RznYfWp7HHwCPXtd3sje4JVgKzuq7OzBJ0VUOiuCn5c4MS7kA9Rpr86J/bmCmujoEWcZWYoQZgZAw+l51umBMlDT4R+Xsme0WyYPuSpRIp/aRsHAyBla0johaZPqe2NeXG3atSTofT82rotXU5QQkV0ggbU9oYcPpIekaMZAEATJMzz1cuWvFibTP0YIPBw/1ulqB1d/XxDccJnQy2d6EOfFMLSOPnNc/kumsym2kuDQbvw7c8nPdWLo4mOmNSrPiqmPjCKjLlVWaWiX/5P5pUQuUnMcL05S45KsDrPnN+WtvQcD1L0JWswVcjMrfqR99yxOZBh3FGHc4YoVy5+OOmBoWzUcmjywMcdb3gVgTLNF4eMnHRoPaW+CtwILDp8qFe9IoufEnL63Y143oc5yd/C0aNvpFXFvrHhdSYbJU9besdNqv5mThWvZ/HumndCFcuDPqoGW6k0JuhJmwge/1Uh69VA4lS5U=
  file: "$RELEASE_TAR"
  on:
    repo: PurpleBooth/jira-branch-helper
    tags: true
    overwrite: true